version: '3'

services:
    instaddicted:
        build: .
        deploy:
            restart_policy:
                condition: unless-stopped
        env_file:
            - ./env
        networks:
            - localworld
networks:
  localworld:
    external:
      name: localworld

